# Generated by Django 5.2 on 2026-08-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_invoiceanalysis_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceanalysis',
            name='est_en_regle',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='invoiceanalysis',
            name='nb_criteres_ok',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceanalysis',
            name='objet_commande',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceanalysis',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceanalysis',
            name='type_objet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiceanalysis',
            name='user_first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='invoiceanalysis',
            name='user_last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
