# Generated by Django 5.2 on 2026-08-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invoiceanalysis_est_en_regle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceanalysis',
            name='full_report_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
