# core/fournisseurs_list.py
"""
Liste des fournisseurs avec lesquels SOMAS travaille.
À partir de la liste fournie.
"""

FOURNISSEURS_SOMAS = [
    "ACTEMIUM",
    "AFRIQUIA SMDC",
    "AFTIC",
    "AGORA TECHNOLOGY",
    "ALUSTORE sarl",
    "ANIR MEDIA sarl",
    "ANTEA GROUP",
    "APAVE MAROC",
    "ATLAS COPIE",
    "AVANTI",
    "BEN SECURITE SYSTÈME",
    "BENZ REQ",
    "BI GENERAL",
    "BRICOMA",
    "CALL & DRIVE",
    "CASH SERVICE sarl",
    "C.B.E / Construction de Bobinage Electrique",
    "CEGELEC S.A.",
    "COM GC s.a.r.l",
    "DRILLSTAR",
    "ECOGEO sarl",
    "EFFICIENCE ENGINEERING s.a.r.l",
    "ELEC PARTNERS",
    "ENGENGAS",
    "ENI",
    "ENJEU sarl",
    "ERAS GROUPE",
    "EXPERT EYE ENGINEERING",
    "FEDAFLEX",
    "FKG Maroc sarl",
    "FLODIM sarl",
    "FMC Technologies SA",
    "FRANK'S France",
    "FXL INTERNATIONAL sarl",
    "GS2I",
    "IMPRICOM",
    "ITECO Oilfield Supply France",
    "JENATECH",
    "KIT INFO",
    "LICORNE",
    "LOCASOM",
    "LUANCE S.A.R.L",
    "MANUDEM MAROC",
    "MAROC TOPO",
    "MEN INDUSTRIE",
    "MESMARI DE MAINTENANCE INDUSTRIELLE",
    "MMC ENGINEERING",
    "MONDE BUREAUTIQUE",
    "MPAS",
    "MPC -MEASUREMENT PROCESSING CONTROL SARL",
    "Network Connectivity S.A.R.L",
    "OULMES VOYAGES",
    "PREDICT S.a.r.l",
    "PRO SYSTEM",
    "PROMACT",
    "PROTEC INCENDIE",
    "REACT COM",
    "RH CONCEPT",
    "S DESIGN",
    "S2A INDUSTRIE sarl",
    "SAAD EQUIPEMENT Sarl",
    "SCHLUMBERGER",
    "SERVOPRES sarl",
    "SGS Maroc SA",
    "EFFIENCE MANUFACTURING",
    "SIAE s.a.r.l",
    "SIATRA sa",
    "SMITCH sarl",
    "SN INDUSTRIE",
    "SOMAREST",
    "SONARI sarl",
    "SONEFI",
    "STATION TOTAL DU PARC",
    "STROC INDUSTRIE",
    "SUD ROBINETTERIE Industrie",
    "TC MAROC S.A",
    "TECHNI DISPO sarl",
    "TECHNIPRO sarl",
    "THALES",
    "THE NEXT VISION",
    "TOFCO MAROC",
    "TOPOGEOMA",
    "TOUR ET FERE s.a.r.l",
    "TRACTAFRIC SA",
    "QUALITAS",
    "TRAREM AFRIQUE",
    "UMANEX PROTECTION",
    "YALIM SERVICES",
    "YOUSRALLAH sarl",
    "APAVE SUDEUROPE",
    "BUREAU VERITAS MAROC",
    "ERAS",
    "M-I SWACO, A Schlumberger Company",
    "SRI",
    "TOTAL",
    "TRANS 2",
    "CA2E",
    "CAPFI sarl",
    "EAGLE ENGINEERING",
    "ESDATA",
    "FER 7 DIFFUSION",
    "GEOSTOCK SAS",
    "LYDEC s.a",
    "MAROC TELECOM",
    "MEDITEL",
    "Polluclean",
    "PRECIA MOLEN MAROC",
    "ABB MOROCCO",
    "AFRI SECURITE",
    "ALWANI TRAVAUX",
    "ANDREATEK",
    "A.R.F.I",
    "ASSIL TEC",
    "ATLAS HOTEL",
    "BEN PROD sarl",
    "DELTA INDUSTRIE",
    "DETAIL INOX",
    "EDITION KENZA",
    "ELEXPERT sarl",
    "EMERSON",
    "Emerson Process Management",
    "ENDRESS HAUSER",
    "FG INDUSTRIE",
    "FLOWSERVE B.V.",
    "FLOWSERVE SIHI S.A.S.",
    "G T R",
    "I3E",
    "IMRI",
    "INFO COPIE",
    "L.P.E.E",
    "MADCOMA",
    "OUSSAMA SARL",
    "ROTORK MOTORISATION",
    "SOFIMED",
    "2MIC",
    "A à Z Pesage S.A.S.",
    "A. Silva Matos, S.A.",
    "ADIGO",
    "AEON PERFORMANCE",
    "AFAQ",
    "AFEM",
    "AFIT",
    "AFRIQUIA GAZ",
    "AHMED MIKOU",
    "AIRLITEC",
    "ALD AUTOMOTIVE",
    "ALLIED INTERNATIONAL FRANCE",
    "ALPHA ASSURANCE",
    "ALTECH Ingénierie",
    "Amphitrite Beach Hotel",
    "ANAIS",
    "APRO INDUSTRIE",
    "ARPEGE Master K",
    "ASSISTEC",
    "Athisa Maroc",
    "ATLANTIC DEMENAGEMENTS",
    "Atlas Copco Maroc SA",
    "Atlas Kounouz",
    "ATOUT LOCATION",
    "ATRAL S.A.R.L",
    "AUXEL",
    "ARTELIA Maroc",
    "Axfam Maroc",
    "B D O",
    "BARNEOUD",
    "BEC FRERES",
    "BENYA ENGINEERING",
    "BESI CONSEIL",
    "BETATEC INDUSTRIE",
    "BICAT",
    "BUZZICHELLI MAROC",
    "C m2d",
    "Cabinet architecture ABDELADIM M'HAMDI ALAOUI",
    "CAM",
    "CAMERON ROMANIA S.R.L.",
    "CANA PRINT",
    "CAPEP",
    "CASA INTERCLIMAT",
    "CASA MAZOUT",
    "CCTI",
    "CENTRALOC",
    "CGR",
    "CHAABI LLD",
    "CHAKRI TAIBI",
    "CHEROFRANCE",
    "CID",
    "CIRGEC MAROC",
    "CMI",
    "COFOR",
    "Compresseurs Worthington-Creyssensac",
    "CORPORATE TELECOM",
    "Corus",
    "DABA NESPRESSO",
    "DE VIRIS",
    "DEFIBTECH",
    "DELATTRE LEVIVIER MAROC",
    "DIBAKOU SARL",
    "DIGIBAY ELECTROPLANET",
    "DISTRITUBE SA.",
    "DNV",
    "DOUNIA CHIMIE",
    "DROGUERIE TISSINT",
    "DylanFrance S.A.S",
    "EAGLE EYES",
    "Eaux de Marseille Maroc",
    "ECO PROTECTION",
    "Ecomed",
    "Ecoval Maroc",
    "EGBS",
    "EGFI",
    "EGIDA PROPRETE",
    "ELCOR",
    "ELLATRA",
    "EME - FC",
    "EMMSA",
    "EMT LEVAGE",
    "ENTREPOSE",
    "Equip Fluid",
    "EQUIP'FLUIDES",
    "ESTORS SERVICES",
    "EURETEQ",
    "EURO NET INTERIMA",
    "EZZIDI KHALID",
    "Faure Herman SAS",
    "FCE",
    "FED MONTAGE",
    "FEDALA DECO",
    "FIRCOM SYSTEME sarl",
    "FIRM",
    "FORCE METALLIQUE SARL",
    "FOURELAGADEC",
    "G.L.I. (Gaz Liquéfiés Industrie)",
    "Galperti",
    "GARAGE ZIOUANI",
    "GARDNER DENVER",
    "GENOYER",
    "GLI",
    "Groupe Eagle Eyes Service",
    "Groupe TFE -Techniques Françaises d'Export",
    "HAGER HOTEL",
    "HARRY OPEN",
    "HOFIT",
    "HYDAC INTERNATIONAL",
    "I D P",
    "I.T.S Piping",
    "IndusTrade Solutions sarl",
    "INSTITUT PASTEUR DU MAROC",
    "ISO MONTAGE",
    "JM System sarl",
    "Kanban entreprise",
    "KDI",
    "K.P.M.G s.a.",
    "KRHOHN",
    "KSB",
    "KSB Pompes et Robinetteries SARL",
    "KSB SAS - Agence Rhône-Méditerranée",
    "LADCI-SOMADU",
    "L'AMPHITRITE BEACH HOTEL",
    "LARES sarl",
    "LE BIT",
    "LEG BTP",
    "LES EAUX MINERALES D'OULMES",
    "LES EQUIPEMENTS INDUSTRIELS",
    "LEY & FUXA",
    "LINEA",
    "Logipro",
    "M.C.R. association",
    "MACOMA",
    "MAGHREB OXYGENE",
    "MARENNO TRANS",
    "MARIONNAUD",
    "MARJANE HOLDING",
    "Maroc Montage",
    "MAROCAINE GRUE",
    "MASBAHI GROUPE INFORMATIQUE",
    "MASIFE",
    "MASONEILAN – GE ENERGY SERVICE",
    "MATERIAUX EL KHAIR",
    "MECA INOX S.A.R.L",
    "MECANIUM SARL",
    "MGI EQUIPEMENTS",
    "MIMOSAS CONTRÔLE INDUSTRIEL",
    "Mitsui",
    "MOBILIA",
    "MOHAMED ALJ",
    "MOTIVATION & EVENTS",
    "MRC Global (France) SAS",
    "NEVATEL",
    "Nitam",
    "NOBLCOM",
    "NOVAIR",
    "NOV-Downhole Eurasia Ltd.",
    "NUM R.S",
    "ODARIS",
    "OGEC",
    "ONEP",
    "OUISELSAT",
    "PEMAVAC",
    "PLASTIMA",
    "POCEVA",
    "POWER NETTOYAGE",
    "PRO ENERGIE",
    "PRODIGE",
    "PRO-ENG",
    "PROTEGE MAROC",
    "PROTRAD",
    "PSIM sarl",
    "Red textile",
    "Replay Plast",
    "RESTAURANT DU PARC",
    "RESTAURANT DU PORT",
    "RESTAURANT SANS PAREIL",
    "RIO",
    "Rmd recuperacion",
    "ROUSSEAU DISTRIBUTION",
    "S M I E A    PC",
    "S2G sarl",
    "S2M INDUSTRIE SARL",
    "SABAH HOTEL",
    "SAGEMINES-GEORS",
    "Mannesmann Line Pipe GmbH",
    "SAMIR",
    "SAMSON REGULATION S.A.",
    "SBV - Sern ball valves.",
    "SCHIELE MAROC SA",
    "SECOMAT",
    "Segedema",
    "SEHI",
    "SEPROB",
    "Serv Instrumentation",
    "SERVICE ACIER",
    "SIM(Service d'Intervention sur Mesure)",
    "SIRAGA",
    "SIRI",
    "Sita ElBeïda",
    "SMAC",
    "SMPC",
    "Smrr",
    "SMS",
    "SN MARCO",
    "SOCITRAG",
    "SODEXO",
    "Sofresid SUD EST",
    "Sofresid SUD OUEST",
    "SOGEA",
    "SOGETUB",
    "SOLUTION TELEPHONE COMMUNICATION",
    "SOMADU",
    "SOMAPEINTURE",
    "SORABO SARL",
    "SORAFLEX",
    "Sorepac",
    "SOUDMETAL",
    "SPIE",
    "SRL SA",
    "STERLING FLUID SYSTEMS",
    "Sterling Fluid Systems (France)",
    "Sublime industrie",
    "SUCCESS PUBLICATIONS",
    "SUDAC AIR COMPRIME et AZOTE",
    "SYS CONSULTING",
    "T E H",
    "TARGET WELL CONTROL",
    "Target Well Control France",
    "TCCM",
    "TECHINTER MEDITERRANEE",
    "TECHNIFEU - MAROC",
    "Techniplus, Konecranes Maroc",
    "TECHNITEST",
    "TECMECA - PACQUET",
    "Tecmed Maroc",
    "Teodem",
    "Thyssen krupp mannex",
    "TOP NEGOCE sarl",
    "TRAITEUR FLEUR BLANCHE",
    "TRAVAUX TRANSPORT KASSED",
    "TUV",
    "TYCO VALVES",
    "UNIFORCE INFORMATIQUE",
    "Univers électrique",
    "VIVENTY",
    "Weatherford Oil Tool GmbH Tunisia Branch",
    "Weatherford Holding BVI Ltd Morocco",
    "WESSLING Maroc",
    "WHESSOE",
    "ZAHIR INDUSTRIE SARL",
    "GFI sa",
    "3S MOROCCO",
    "Performance Service sarl",
    "CBI",
    "Amadil Express",
    "Computime",
    "ATCOMA",
    "IM CONSO",
    "ITRANE INDUSTRIES",
    "ECO SECURITE MAROC",
    "CABINET HDID CONSULTANTS",
    "PULLMAN MAZAGAN ROYAL GOLF & SPA",
    "AHMED LAKSIWAR",
    "AFRAH FES",
    "ENSIVAL MORET SERVICES MAGHREB",
    "MAROC PERFORMANCE (Groupe INNOV MAROC)",
    "MOHAMMED AMINE",
    "MAROC CULTURES",
    "INSTITUT MULTIHEXA CASA sarl",
    "E.T.M.I s.a.r.l",
    "ASSIL BTCM SARL",
    "LENOS Engineering s.a.r.l",
    "A.Z MANUTENTIONN SARL",
    "OPTIMA DE PROTECTION INDIVIDUELLE ODPI.",
    "CFG CONSEIL",
    "EPIMAR SARL",
    "M.E.C.F s.a.r.l",
    "CENTEC S.A.R.L",
    "JOLOF SYSTEM",
    "RADIOLOGIE OUED EL MAKHAZINE",
    "BDO Sarl",
    "FLOWSERVE BV-FLOW SOLUTION GROUP",
    "FLOWSERVE POMPES SAS",
    "TECNOSUB MAROC SARL",
    "Ste. JALOUAJA SARL",
    "CONNECT IN",
    "OURIKA MONTAGE SARL",
    "XECOTEC S.A.R.L",
    "LOCAMED SERVICE",
    "Sté BROUKSY SERVICE RAPIDE",
    "HOTEL FEDALA SARL",
    "AUTO NOUHAILA SARL",
    "ALTITUDE RH",
    "MAHARA S.A.R.L",
    "SMITREL SARL",
    "DELTA RH S.A.R",
    "INASS BUREAU TECH",
    "MEM",
    "AHMED AOUANI",
    "REACONCEPT SARL",
    "Fer7",
    "OPTIM ESPACE",
    "FEREMBAL MAGHREB SARL",
    "LADCI S.A.R.L",
    "3PSC",
    "EXPERT CONSULTING SARL",
    "DISTY TECHNOLOGIES SA",
    "EATON ELECTRIC SARL",
    "REKRUTE SARL",
    "INSTITUT MAROCAIN DES ADMINISTRATERUS",
    "Recherche Developpement Industrie",
    "PROCESS INSTRUMENTS SARL",
    "G2I SARL",
    "ECORMI SARL",
    "ATLAS GLOBE MAROC SARL",
    "MAROC PESAGE",
    "A.F.E.M",
    "GLOBAL TRADE INDUSTRY",
    "Dr Kettani Mohammed Najib",
    "ENGINEERING MAESURES",
    "ADVANCED AUTOMATION",
    "TIME 4 ACTION S.A.R.L.A.U",
    "ABRAJ DAY PLUS sarl",
    "BLEUSAM sarl",
    "FCC INDUSTRIES",
    "S.G.I.S",
    "Technique Equipement Hydraulique Sarl",
    "FINANCE SYSTEMS SARL",
    "GENERAFI",
    "TECHNOSUP",
    "SRTIES S.A.R.L.AU",
    "TECHNIPIPE",
    "ELETECHNIK MAROC",
    "NCL EXPORT S.A.S",
    "IPSI",
    "ZIZ",
    "BICOP Sarl",
    "INTERVARIA",
    "Déco Pro S.A.R.L",
    "MED PROTECTION SARL",
    "SMARTING SARL AU",
    "QUALITE CONTROLE MESURE (QCM)",
    "INSTRUMAR SARL",
    "LES AUTOMATISMES APPLIQUES",
    "SHAREM S.A.R.L",
    "DS SERVICE s.a.r.l",
    "GREENTHERM SARL",
    "MAROC SEALING SARL",
    "TALENT ACCESS SARL",
    "BEST PROFIL",
    "ALJIBAT",
    "ENTREPRISE ABDELKAHAR SARL",
    "Campus de l'UIR",
    "ATLAS AGENCEMENT",
    "PHARMACIE MESBAHIATE",
    "NAVARA BURO",
    "CCMBURO SARL",
    "Univers Digital S.A.R.L",
    "LE PLAISIR D'APPRENDRE SARL",
    "Crescendo Baby Music",
    "DREAM VILLAGE",
    "BOUGTECHNIC PLUS",
    "Ste CONSSOUFRANCE s.a.r.l",
    "Layher Maroc Echafaudage",
    "FENIE BROSSETTE SA",
    "Riegonor s.a.r.l",
    "GENERAL ENGINEERING BUILDING",
    "HALADJIAN MAROC",
    "MOBIFAR SARL",
    "SOMALEV",
    "PCB PIEZOTRONICS",
    "Protection Unit",
    "TECHNITAR sarl",
    "EMEFCIE MAROC SARL",
    "Afric Roulement",
    "TÜV Rheinland Industrie Service GmbH",
    "TRAPIL",
    "ROSEN EUROPE B.V.",
    "Tennaxia Consulting SARL",
    "ESPACE LAMHA s.a.r.l",
    "IPCONFIG",
    "APTITUDE CONSEIL",
    "SRM sa",
    "POL IT sarl",
    "DIORH",
    "HIGH GLOBAL SERVICES",
    "MISSGOU",
    "ENGINEERING MAINTENANCE TRAVAUX sarl",
    "PETROLEC SARL",
    "FM TECHNOLOGY SARL",
    "JORY INDUSTRIE Sarl",
    "SOLUZIONE",
    "EURAFRICAINE DE MATERIELS sarl",
    "Espace Marina sarl",
    "PETRONACO",
    "MATER INDUS sarl",
    "SAMIREG sarl",
    "PASFO MAROC sarl",
    "ETS RESELEC SARL",
    "MAYMAR sarl",
    "TECHNIQUE RESEAUX SYSTEM sarl",
    "PETROPREMA",
    "BESTMARK",
    "DIGIBAY",
    "ERMAP SARL",
    "SORELECA sarl",
    "MARCO METAL sarl",
    "CHAMBRE FRANCAISE DE COMMERCE ET D'INDUSTRIE DU MAROC.",
    "VALTECH S.A",
    "LEEIM",
    "INNOVATECH ENGINEERING",
    "DATAPROTECT sarl",
    "6TECH Solutions",
    "ECO ELEC",
    "NORMINDUS sarl",
    "MAGELECT sarl",
    "AUTOMATION TECHNIQUES",
    "ULTRA BUREAU sarl",
    "BEAUTY DESIGN",
    "GFI",
    "OUTIFLEX sarl",
    "SCOMEDICA s.a.r.l.a.u",
    "MATAM sa",
    "AKSALAB",
    "AGROVET LABO",
    "FLOW TECHNIQUE MAROC sarl",
    "MGMT sarlu",
    "LAGHCHIOUA SERVICES sarl",
    "CANET LEVAGE sa",
    "Flowserve Morocco sarl au",
    "ETS BAZI EQUIPEMENT sarl",
    "Defib Maghreb sarl",
    "MCC Measurement Control Center sarl",
    "L2MI",
    "RIG ALTEA",
    "A.N.K. SYSTEMS",
    "FPS Maroc",
    "E²Consult sarl",
    "PH&R sa",
    "BKHS sarlau",
    "American Language Center",
    "ELENACO sarl",
    "NET ENERGY sarl",
    "ARTTHERE",
    "DMC MAGHREB",
    "MAXI SECURE",
    "COFAL sarl",
    "STROB sarl",
    "SMETRAP sarl",
    "DATA PROCESS",
    "I2S TESTING sarlau",
    "FIABEL",
    "TECNOFFSHOR sarl",
    "NADI ASSAINISSEMENT",
    "ESCA sarl",
    "RACOSY sarl",
    "HAMELLE MAROC",
    "PEINSO Revet sarl",
    "BUINCO sarl",
    "Digital and You",
    "SOFT SEVEN ART",
    "PhB Conseillers",
    "EFBB sarl",
    "ARTEMIS sa",
    "TELSTAR sarl. AU",
    "SIRMEL s.a",
    "SIREX sarl",
    "SEREC",
    "TEAM TEC sarl",
    "INSTALLATOR sa",
    "LOGINFO INGENIERIE sarl",
    "VM SECURITE s.a.v",
    "ACTI SECURITY sarl",
    "INNOMEC sarl",
    "LOTF TRANS",
    "AET",
    "VALVTEC sarl",
    "INDUSELEC sarl",
    "SYNTHESE CONSEIL",
    "Merkatis sarl",
    "SECURITE INCENDIE SAUVETAGE MARITIME CASABLANCA",
    "AL3A sarl",
    "LOTF TRANS.",
    "GLOBAL MATERIEL sarl",
    "ROCK BAT sarl",
    "E2CONSULT sarl",
    "SOMINFAC",
    "BRICOMA",
    "Société d'Ingenierie et de Construction Industrielle",
    "HTGC HIKMAT sarl au",
    "DELTA BUREAU s.a.r.l",
    "SIGN MARK sarl",
    "2M-INST sarl",
    "BARTEC S.à.r.l",
    "Maghreb Automatisation Sarl",
    "Maroc Archivage",
    "DOC'ARCHIVES",
    "ARCHIVEX",
    "FORTRADE sarl",
    "Partners Synergie Africa",
    "SOCIEDAD DE TRANSPORTE DE GAS Y MERCANCIA sarl",
    "MATGEC - SOCIETE MAHDIA TRAVAUX DE GENIE CIVIL sarl",
    "NOVOTEL MOHAMMEDIA",
    "METALOUTIL",
    "CONSOCENTER",
    "GLOBAL MANUTENTION",
    "MOHAMED CHORFI",
    "O'Pub s.a.r.l",
    "GLOBAL AMENAGEMENT",
    "ENGIE CONTRACTING AL MAGHRIB",
    "AMED TECHNOLOGIE sarl",
    "MRCO COMPANY sarl",
    "LE BUREAU MODERNE",
    "FULLAMTIC sarl",
    "3i Solution Consulting",
    "The International Safety College",
    "VIBRA MOTOR MAROC sarl",
    "Sté. Les Grands Travaux Routiers",
    "MEDIA ELECTRO TECHNIQUE sarl",
    "ZAGOMETAL sarl",
    "DIGIBAY SA",
    "COSMOS ELECTRO",
    "TRADI-GOURMET sarl",
    "LYCOM CONSULTING sarl",
    "Ste RICHESSE DE CONSTRUCTION sarl",
    "SOCIETE TECNA",
    "SFIS sarl",
    "DRON MAROC s.a.r.l a.u",
    "SPHINX sarl",
    "COACH Consulting",
    "SERV'AGENCY",
    "DARCO SAS",
    "MOHAMMEDIA LANGUAGE CENTER",
    "METAL CONSTRUCTION INDUSTRY sarl",
    "BUREAU TRAD",
    "LOXA DRIVE sarl au",
    "HARTMANN Valves GmbH",
    "TENARIS GLOBAL SERVICES S.A.",
    "Vallourec Oil and Gas France",
    "Matériel Incendie Maroc",
    "KING SYSTEMS sarl",
    "CAMERON FRANCE S.A.S",
    "ABDL INDUSTRIE",
    "SIMN MAROC sarl au",
    "LAMPELEC sarl",
    "MUSTAFA DAROUICH - ARCHITECTE",
    "CAMERON Romania",
    "Industriel Mecanique General sarl",
    "SOCIETE MAROCAINE DE PROTECTION INDUSTRIELLE sarl",
    "AUDINA",
    "MAROC HYGIENE PUBLIQUE sarl",
    "SERPRO sarl",
    "NABOCCO sarl",
    "AUXITEC INDUSTRIE",
    "IMETAL sarl",
    "FEDALA COMPUTER sarl",
    "MOTIVE MOROCCO SOFTWARE",
    "MAROC COATING & CORROSION CONSULTING sarl",
    "MISTRAS GROUP",
    "IRH sarl - INSTITUT RESSOURCES HUMAINES",
    "ELECTRO TAOUIMA sarl",
    "CNPP Afrique sarl",
    "ETEN sarl",
    "TPE sarl",
    "COGIME sarl",
    "INGENIERIE MESURES",
    "Schlumberger Overseas S.A.",
    "Weatherford Oil Tool GmbH S.a.r.l",
    "PAF SECURITE sarlau",
    "PETRO SURVEY",
    "TRAITEUR AFRAH BLADI sral au",
    "MAGICLED",
    "KS TECHNOLOGY",
    "BLEU ENERGY SERVICE",
    "GOLD COSMETIC",
    "SAPEM sarl",
    "SOFIA VALVES SAS",
    "PETROTANK",
    "Numéricom",
    "Flowserve SIHI (Spain), S.L.",
    "PESAGE PROMOTION",
    "IMPRICOM MAROC",
    "FIREPRO ENGINEERING sarl",
    "Ste. TIBA Oil Tools sarl",
    "Votre Com",
    "BEBAC sarl",
    "MEDICAR SAFETY sarl",
    "BWM CONSULTING",
    "COMMERCIALE TUBI ACCIAIO",
    "GRAVSER",
    "SRMH TRAVAUX sarl",
    "Halliburton B.V.(SUCC) , Moroccan Branch",
    "RESERVOIR GROUP",
    "Mediterranean Oilfield and Consulting Services France (MOCS)",
    "BEARN OPERATIONS POMPAGES SERVICES (BOPS)",
    "APAGEO",
    "MUSTANG OIL SERVICES",
    "CVA Wells",
    "Newpark Drilling Fluids Morocco Branch (Succ)",
    "FRANK'S INTERNATIONAL WEST AFRICA BVI LTD - MOROCCO BRANCH.",
    "YGD CONSEIL",
    "INTERSICA",
    "SOLASOL sarl",
    "ROMA FOURNITURE sarl",
    "G5TD",
    "SOMEQUIP sarl",
    "DOJA TRAVAUX sarl",
    "GEOPHYCONSULT SAS",
    "RDSE sa",
    "KHALSI",
    "NOV DOWNHOLE Eurasia Ltd",
    "UMEL sarl",
    "INGEN INNOVATION POUR LES GOESCIENCES.",
    "ISTeP Institut des Sciences de la Terre de Paris - UPMC",
    "MAROC CONTENEURS",
    "KAYA GENERAL",
    "TRANSPORT CG",
    "Société Nationale des Transports et de Logistique - SNTL",
    "NEWPARK DRILLING FLUIDS TUNISIA BRANCH",
    "AVAL Nord Afrique sarl",
    "SANI ASSAINISSEMENT sarl",
    "MISSION PROTECTION",
    "INDUS COMASER sarl",
    "SKILLSOLUTIONS sarl",
    "NEWPARK DRILLING FLUIDS S.p.A",
    "INTERO Integrity Services B.V.",
    "PDS",
    "TAM International North Sea Limited",
    "HOTEK ENREGY sarl",
    "ALLIANCE VOYAGE",
    "ATS Lifting Energy",
    "Maroc Afrique Assistance",
    "CREATINE sarl",
    "GEOFACTORY Spain S.L",
    "ARMINES",
    "IZAK",
    "ESSABEL CO sarl au",
    "EXOL sarl",
    "ASWAK ASSALAM",
    "SO SOLUTION sarl",
    "OPERATIONS SOUS-MARINES SPECIALES (OSS)",
    "DRAPOR",
    "MECATORK ACTIONNEURS SAS",
    "CROP & CO",
    "STE NAMI TECH sarl",
    "CAIDELEC sarl",
    "GENERAL EQUIPEMENT ET INSTALLATION INDUSTRIELS.",
    "SOBEAM sarl",
    "NOTEMAC sarl",
    "Ministère de la Transition Energétique et du Développement Durable",
    "Tectra sarl",
    "STFS sarl",
    "Inetum Maroc SA",
    "Novation Technologies",
    "FARAJ METAL",
    "Cabinet d'Architecture Hicham MALTI",
    "Atelier BW",
    "Atelier FF sarl",
    "COOPERATIVE AL MONAKH SERVICES",
    "SEKERA Services",
    "EXPRO Overseas Inc – Dubai Branch",
    "MOROCCO SAFETY TRAINING sarl",
    "LMPS",
    "GLOBAL PRO ENGINEERING",
    "ANALYTIC LAB",
    "SNEP",
    "MEDI MONTAGE",
    "AFRICAWORK MAROC sarl",
    "EVOE CONSULTANTS",
    "VALVAN",
    "MLAK Abdelilah",
    "FRANK'S INTERNATIONAL MIDDLE EAST FZCO",
    "Management Gouvernance Ingénierie Consulting - MGIC.",
    "Audit Conseil Formation sarl",
    "LE PONT MEDITERRANEEN sarl",
    "IZY TARGET",
    "IDUNA GEOPHYSIQUE sarl",
    "Vergès sarl",
    "CADILHAC",
    "SAHN TEC",
    "AZURE NETWORKS COMPANY INTL",
    "CIU PEDAGOGIQUE SA",
    "Nadaf Service Maroc",
    "HYPROM",
    "SQUARE ONE",
    "FIRST SHOP",
    "CONSUMER VOICE sarl",
    "EMERSON FZE",
    "ALPHA EXPERT",
    "I.C.E.C",
    "OUSSAAD NEGOCE",
    "MTEL GROUP",
    "CONFIA",
    "ALLIANCE GSP",
    "APPROVISIONNEUR TECHNIQUE INTERNATIONAL",
    "SUBLIME INDUSTRIE",
    "BLOCKTECH sarl",
    "ATLAS SURVEY sarl.au",
    "DALITRANS",
    "STEP FOR DEVELOPPEMENT sarl",
    "LIFEMOZ BUSINESS",
    "NASSFLEX sarl au",
    "CLEVER COUNCIL",
    "ETESCO ENGINEERING",
    "PROSTEEL",
    "ITABE ACADEMY",
    "Sté MOHAMMEDIA TUYAUTERIE ET CHAUDRONNERIE",
    "HYDRAUTECH INDUSTRIE",
    "ZIRAOUI CAR",
    "KC PROTECTION",
    "AUTOMATION EXPERTS",
    "CONCEPT-INDUSTRIES",
    "DECATHLON Maroc sas",
    "ALLO PRO",
    "FOCUS PROJECT",
    "ECO TOILETTE",
    "NEW ART PRINT MAROC",
    "KAMED SELECT",
    "ABDELLATIF MITRAB",
    "J.WAS JOB PRIVE",
    "CAMELIA GREEN",
    "SIGNALISATION DU MAROC",
    "FIMATOOLS",
    "SOLATRAVIT",
    "LAND ART",
    "EMEQIP",
    "FIRCOM SYSTEMS Ingénierie sarl",
    "SYNERGATES",
    "Sté BENHAMOU",
    "Msefer et associés SARL",
    "QUALI CONTROLAB",
    "L.G.D.O.R",
    "GREEN CENTER",
    "BMB STUDIO",
    "RAGHAD GARDEN",
    "POLYGEO sarl",
    "WAVE INDUSTRIE",
    "INERIS formation SAS",
    "Kinedispo",
    "Dr BERRADA Ali",
    "OCA GLOBAL",
    "ABC ENGINEERING - AFRICA BUSINESS COMPANY ENGINEERING",
    "Sté. FORACO TP sarl",
    "Société NADAMAR MAROC",
    "Bureau Véritas Solutions",
    "DEEP MARINE (EX BLEU ENERGY SERVICE)",
    "AI SYSTEMS",
    "DIRECT OFFICE",
    "E&B CONSULTING",
    "MTT Expertises",
    "NYB CONSULTING",
    "Roux Afrique",
    "CAPELLA ENGINEERING",
    "BEVEC Engineering & Consulting",
    "LE KIOSQUE DISTRIBUTION",
    "TAMESNA VERT",
    "AQUARELLE FLEUR",
    "TRADI GOURMET",
    "EFFICIENCE MANUFACTURING",
    "VIAS",
    "Ste. MANUEVA sarl.au",
    "Target Com",
    "Cible Plus",
    "CODE EVENT",
    "SOTECHPRO",
    "CT INSTRUMENTS",
    "MARKAS",
    "Sté. RM-PROTECT sarl.au",
    "LES FEES COM",
    "BOM ROBINETTERIE",
    "CoreValue",
    "FUTURATE",
    "SAHARA MOBILIER",
    "TABA SARL",
    "TAPIMOMO",
    "INDUSTECH-PRO ÉQUIPEMENT",
    "Caldererías Indálicas Maroc (CIM)",
    "ECOFIT ENERGY",
    "LE PREVENTEUR",
    "LES TECHNIQUES DE TARAGE",
    "IPS SUPPLY SAS",
    "O'PUB",
    "ORSAP",
    "REVEL MAROC",
    "M-job",
    "SINALUX",
    "DOOC Consulting",
    "BOUTAYNA ABBAD EL ANDALOUSSI - INTERIOR DESIGNER",
    "ANAS OUABARE - Architecte d'interieur",
    "NATUREL DESIGN",
    "2MIC",
    "AI Crafters",
    "ACADEMIE INTERNATIONALE DE FORMATION",
    "INSIGHT COACHING",
    "ECVM - Engineering Control Vibration Maintenance",
    "LYON BOBINAGE",
    "EMC",
    "NEVOLYS CONSULTING",
    "INETUM SOFTWARE MOROCCO",
    "QualiMet Maroc",
    "HEXAGON GEOSURVEYS",
    "MCL ( Moroccan Calibration Laboratory)",
    "CORINTH PIPEWORKS S.A",
    "ICON",
    "LABSOL",
    "CTTI - Contrôle technique travaux industriels",
    "AMS AFRIQUE SERVICE",
    "AFRIQUE LEVAGE",
    "LABORATOIRE DE CONTROLE INDUSTRIEL ET DE L'ENVIRONNEMENT",
    "FIRST4COM",
    "Groupe Premium",
    "ASTRI SOLUTION",
    "Archerwell",
    "TCERT MOROCCO",
    "NABORS",
    "LAINE MECANIQUE",
    "BM FLEX",
    "Green Lab Solutions",
    "ARCHITECTE NAJIB BERRADA",
    "AMSPEC MOROCCO",
    "MENA Survey",
    "EPITAPHE 360",
    "Utopia Agency",
    "Audicompliance Consulting",
    "Tichetti Ahmed",
    "Weatherford Worldwide Holdings GmbH",
    "ONHYM - Office National Des Hydrocarbures Et Des Mines",
    "BLK ADVISORY FIRM",
    "H.Laafou & Associés",
    "Africa Law Firm",
    "GIDE MAROC",
    "AFRIQUE ADVISORS",
    "CABINET LAAFOU CONSEIL",
    "El Mekki Assainissement",
    "VACUM marine & industrie",
    "ATOUTLOC",
    "Q&Q CONTROL SERVICES MOROCCO",
    "BLANCHTOO",
    "AKSA MOROCCO",
    "ENSET Mohammedia - Université Hassan II de Casablanca",
    "ON TEAM evolution",
    "LFP - Build your event",
    "COST HOUSE",
    "ASSESSMENT RH",
    "Dr IDMAHMED Najat",
    "IMARLYS",
    "IMPRIMOS",
    "EPIC COM",
    "SECURITY SOLUTIONS BUSINESS",
    "VENTEC",
    "IMPERATOR INVEST",
    "CONFORMITE 360",
    "SWELL MARINE SERVICES",
    "NOMATER",
    "CASA Dealing",
    "NEXPUBLICA Morocco",
    "SITEF",
    "PROTRASUB",
    "ARTUS RH",
    "ESCA - Ecole de Management",
    "ESITH-Ecole Supérieure des Industries du Textile et Habillement",
    "WAKIPRO",
    "BAITEH WILDING",
    "RESTEL",
    "BERMUDES FOURNITURE",
    "OPAL ERGO",
    "ESHARKI FIRE",
    "EVCO",
    "ARTIZAY",
    "Ecole Nationale de Commerce et de Gestion - ENCG SETTAT",
    "SOMETA",
    "BH LAHLOU EVENTS",
    "Traiteur Essalam",
    "GEVM",
    "MOROCCO RADIO TELECOM - Montel",
    "Netcom Technologies",
    "M2E AUTOMATION",
    "ACAFA - Académie Africaine de l'Energie",
    "EHTE",
    "ROBKE",
    "ARMO",
    "Decrypt",
    "NOVIAX",
     "SIATRA sa",
    "SIATRA s.a",
    "TOTAL MAROC",     # ⭐ Version complète
    "TOTAL SA", 
    "WE LOGISTICS",
    "WE LOGISTICS SARL",
]


# ⭐ Alias pour la recherche (versions simplifiées)
ALIAS_FOURNISSEURS = {
    "apave": "APAVE MAROC",
    "t cert": "TCERT MOROCCO",
    "tcert": "TCERT MOROCCO",
    "we logistics": "WE LOGISTICS",
    "ips": "IPS SUPPLY",
    "maersk": "MAERSK",
    "we logistics": "WE LOGISTICS",
    "we logistics sarl": "WE LOGISTICS SARL",
    "globitrans": "GLOBITRANS",
    "precia": "PRECIA MOLEN MAROC",
    "precia molen": "PRECIA MOLEN MAROC",
    "soge": "SOCIETE GENERALE",
    "societe generale": "SOCIETE GENERALE",
    "bureau veritas": "BUREAU VERITAS MAROC",
    "schlumberger": "SCHLUMBERGER",
    "emerson": "EMERSON",
    "endress hauser": "ENDRESS HAUSER",
    "flowserve": "FLOWSERVE",
    "ksb": "KSB",
    "weatherford": "WEATHERFORD",
    "halliburton": "HALLIBURTON",
    "thales": "THALES",
    "spie": "SPIE",
    "sgs": "SGS Maroc SA",
    "tuv": "TUV",
    "dnv": "DNV",
}